# Generated by Django 5.2.13 on 2026-05-04 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_listingalertsubscription_source_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listingalertsubscription',
            index=models.Index(fields=['is_active', 'category', 'location_city'], name='idx_alert_active_category_city'),
        ),
        migrations.AddIndex(
            model_name='listingalertsubscription',
            index=models.Index(fields=['min_price', 'max_price'], name='idx_alert_price_range'),
        ),
        migrations.AddIndex(
            model_name='listingalertsubscription',
            index=models.Index(fields=['bedrooms_min'], name='idx_alert_bedrooms_min'),
        ),
        migrations.AddConstraint(
            model_name='listingalertsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('max_price__isnull', True), ('min_price__lte', models.F('max_price')), _connector='OR'), name='ck_alert_price_bounds'),
        ),
        migrations.AddConstraint(
            model_name='listingalertsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('bedrooms_min__isnull', True), ('bedrooms_min__gt', 0), _connector='OR'), name='ck_alert_bedrooms_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='listingalertsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('source_property__isnull', False), _connector='OR'), name='ck_active_alert_has_source_property'),
        ),
        migrations.AddConstraint(
            model_name='listingalertsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), models.Q(models.Q(('category', ''), _negated=True), models.Q(('location_city', ''), _negated=True)), _connector='OR'), name='ck_active_alert_has_required_filters'),
        ),
    ]
