# Generated by Django 5.2.14 on 2026-05-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_listingalertsubscription_idx_alert_active_category_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['name'], 'verbose_name': 'amenity', 'verbose_name_plural': 'amenities'},
        ),
        migrations.AlterModelOptions(
            name='listingalertsubscriptionamenity',
            options={'verbose_name': 'listing alert subscription amenity', 'verbose_name_plural': 'listing alert subscription amenities'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyamenity',
            options={'verbose_name': 'property amenity', 'verbose_name_plural': 'property amenities'},
        ),
    ]
