# Generated by Django 5.2.12 on 2026-04-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="scope",
            field=models.CharField(
                choices=[
                    ("AUTH", "Auth"),
                    ("SEARCH", "Search"),
                    ("INTERACTION", "Interaction"),
                    ("TRANSACTION", "Transaction"),
                    ("SYSTEM", "System"),
                ],
                max_length=16,
            ),
        ),
    ]
