# Generated by Django 5.2.13 on 2026-05-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_activitylog_details_activitylog_scope_search'),
        ('properties', '0003_listingalertsubscription_source_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarListingAlertDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similar_listing_alert_dispatch', to='interactions.emailnotification')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_listing_alert_dispatches', to='properties.property')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_dispatches', to='properties.listingalertsubscription')),
            ],
            options={
                'db_table': 'similar_listing_alert_dispatches',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'property'), name='uq_similar_listing_alert_dispatch')],
            },
        ),
    ]
