# Generated by Django 5.2.13 on 2026-05-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_similarlistingalertdispatch'),
        ('properties', '0004_listingalertsubscription_idx_alert_active_category_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarlistingalertdispatch',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='similarlistingalertdispatch',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='similarlistingalertdispatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='similarlistingalertdispatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='similarlistingalertdispatch',
            index=models.Index(fields=['subscription', 'property', 'status'], name='idx_similar_alert_pair_status'),
        ),
        migrations.AddIndex(
            model_name='similarlistingalertdispatch',
            index=models.Index(fields=['status', 'updated_at'], name='idx_sim_alert_status_updated'),
        ),
    ]
