# Generated by Django 5.2.13 on 2026-05-04 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_similarlistingalertdispatch_attempt_count_and_more'),
        ('properties', '0004_listingalertsubscription_idx_alert_active_category_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', False)), name='ck_booking_start_date_required'),
        ),
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', False)), name='ck_booking_end_date_required'),
        ),
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='ck_booking_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='bookingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='ck_booking_status_valid'),
        ),
    ]
