# Generated by Django 5.2.13 on 2026-05-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_paid_statuses(apps, schema_editor):
    Payment = apps.get_model("interactions", "Payment")
    Payment.objects.filter(status="PAID").update(status="COMPLETED")
    Payment.objects.filter(status="REFUNDED").update(status="CANCELLED")


def normalize_orphan_booking_fee_payments(apps, schema_editor):
    Payment = apps.get_model("interactions", "Payment")
    Payment.objects.filter(
        payment_purpose="BOOKING_FEE",
        booking_request_id__isnull=True,
    ).update(payment_purpose="OTHER")


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_bookingrequest_ck_booking_start_date_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            migrate_paid_statuses,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='interactions.bookingrequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16),
        ),
        migrations.RunPython(
            normalize_orphan_booking_fee_payments,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_purpose__in', ['BOOKING_FEE', 'PREMIUM_SERVICE', 'OTHER'])), name='ck_payment_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method__in', ['CREDIT_CARD', 'BANK_TRANSFER'])), name='ck_payment_method_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'COMPLETED', 'FAILED', 'CANCELLED'])), name='ck_payment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment_purpose', 'BOOKING_FEE'), _negated=True), ('booking_request__isnull', False), _connector='OR'), name='ck_payment_booking_fee_has_booking'),
        ),
    ]
