# Generated by Django 5.2.14 on 2026-05-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_simulated_payment_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'property inquiry', 'verbose_name_plural': 'property inquiries'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'search history', 'verbose_name_plural': 'search histories'},
        ),
        migrations.AlterModelOptions(
            name='similarlistingalertdispatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'similar listing alert dispatch', 'verbose_name_plural': 'similar listing alert dispatches'},
        ),
    ]
